named vars

diff --git a/.github/workflows/diff.yml b/.github/workflows/diff.yml
--- a/.github/workflows/diff.yml
+++ b/.github/workflows/diff.yml
@@ -96,22 +96,24 @@ jobs:
           SUBTRACT_BYTES_PER_COUNT: 70
         run: |
           truncate () {
-            cp "$1" "$1.orig"
-            if (( "$2" < 1 )); then
-              printf '\e[31mERROR: %s\e[0m\n' "Negative/null truncate: $2" >&2
+            local file="$1"
+            local size="$2"
+            if (( size < 1 )); then
+              printf '\e[31mERROR: %s\e[0m\n' "Negative/null truncate: $size" >&2
               exit 1
             fi
-            head --bytes="$2" "$1.orig" > "$1"
-            if ! cmp -s "$1" "$1.orig"; then
-              echo -e "\n\nTruncated" |tee -a "$1"
-              tail --bytes=+"$(( "$2" + 1 ))" "$1.orig" > "$1.truncated"
+
+            cp "$file" "$file.orig"
+            head --bytes="$size" "$file.orig" > "$file"
+            if ! cmp -s "$file" "$file.orig"; then
+              echo -e "\n\nTruncated" |tee -a "$file"
+              tail --bytes=+"$(( size + 1 ))" "$file.orig" > "$file.truncated"
             fi
-            rm "$1.orig"
+            rm "$file.orig"
           }
           PS4="\n\033[1;33m$PS4\033[0m"
           set -euxo pipefail
           
-          # git diff
           git -C html diff --diff-filter=M --unified="$DIFF_CONTEXT" HEAD |tee git_diff.patch
           if [ -s git_diff.patch ]; then
             subtract="$(stat -c%s git_status.txt)"
