git status own

diff --git a/.github/workflows/diff.yml b/.github/workflows/diff.yml
--- a/.github/workflows/diff.yml
+++ b/.github/workflows/diff.yml
@@ -72,6 +72,8 @@ jobs:
     runs-on: ubuntu-latest
     needs: build
     steps:
+      - name: Install dependencies
+        run: sudo apt-get update && sudo apt-get install -y splitpatch
       - name: Fetch old HTML
         uses: actions/checkout@v3
         with:
@@ -84,20 +86,21 @@ jobs:
         with:
           name: html_new
           path: html
-      - name: Install dependencies
-        run: sudo apt-get update && sudo apt-get install -y splitpatch
-      - name: Diff
+      - name: Git Status
+        run: |
+          git -C html status --porcelain --untracked-files=all |tee git_status.txt
+          [ -s git_status.txt ] || rm -v git_status.txt
+      - name: Git Diff
+        if: hashFiles('git_status.txt')
         env:
           SUBTRACT_BYTES_PER_COUNT: 70
         run: |
-          # TODO split this into two or more steps?
-          error() {
-            printf '\e[31mERROR: %s\e[0m\n' "$*" >&2
-            exit 1
-          }
           truncate () {
             cp "$1" "$1.orig"
-            (( "$2" > 0 )) || error "Negative/null truncate: $2"
+            if (( "$2" < 1 )); then
+              printf '\e[31mERROR: %s\e[0m\n' "Negative/null truncate: $2" >&2
+              exit 1
+            fi
             head --bytes="$2" "$1.orig" > "$1"
             if ! cmp -s "$1" "$1.orig"; then
               echo -e "\n\nTruncated" |tee -a "$1"
@@ -107,13 +110,6 @@ jobs:
           }
           PS4="\n\033[1;33m$PS4\033[0m"
           set -euxo pipefail
-          
-          # git status
-          git -C html status --porcelain --untracked-files=all |tee git_status.txt
-          if [ ! -s git_status.txt ]; then
-            rm -v git_status.txt
-            exit 0
-          fi
           
           # git diff
           git -C html diff --diff-filter=M --unified="$DIFF_CONTEXT" HEAD |tee git_diff.patch
