error

diff --git a/.github/workflows/diff.yml b/.github/workflows/diff.yml
--- a/.github/workflows/diff.yml
+++ b/.github/workflows/diff.yml
@@ -90,8 +90,13 @@ jobs:
         env:
           SUBTRACT_BYTES_PER_COUNT: 70
         run: |
+          error() {
+            printf '\e[31m=> ERROR: %s\e[0m\n' "$*" >&2
+            exit 1
+          }
           truncate () {
             cp "$1" "$1.orig"
+            (( "$2" > 0 )) || error "Negative/null truncate: $2"
             head --bytes="$2" "$1.orig" > "$1"
             if ! cmp -s "$1" "$1.orig"; then
               echo -e "\n\nTruncated" |tee -a "$1"
